development:
  adapter: postgresql
  encoding: unicode
  database: quoteable_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: quoteable_test
  pool: 5
  username:
  password:
  host: localhost

